import { Routes } from '@angular/router';
import { AboutComponent } from './pages/about/about.component';
import { HomeComponent } from './pages/home/home.component';
import { ServicesComponent } from './pages/servizi/services.component';
import { ContactComponent } from './pages/contact/contact.component';
import { PortfolioComponent } from './pages/portfolio/portfolio.component';
import { PrimiMesiComponent } from './pages/primi-mesi/primi-mesi.component';
import { BebeComponent } from './pages/bebe/bebe.component';
import { MaternitaComponent } from './pages/maternita/maternita.component';
import { SmashCakeComponent } from './pages/smash-cake/smash-cake.component';
import { FamigliaComponent } from './pages/famiglia/famiglia.component';
import { ServiziInEsternaComponent } from './pages/servizi-in-esterna/servizi-in-esterna.component';
import { MiniSessioniComponent } from './pages/mini-sessioni/mini-sessioni.component';
import { RitrattoComponent } from './pages/ritratto/ritratto.component';
import { NewbornComponent } from './pages/newborn/newborn.component';
import { GalleryPageComponent } from './pages/gallery/gallery-page.component';
import { GalleryDetailComponent } from './pages/gallery/gallery-detail.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'chi-sono', component: AboutComponent },
    { path: 'servizi', component: ServicesComponent },
    { path: 'portfolio', component: PortfolioComponent },
    { path: 'contatti', component: ContactComponent },
    { path: 'primi-mesi', component: PrimiMesiComponent },
    { path: 'bebe', component: BebeComponent },
    { path: 'maternita', component: MaternitaComponent },
    { path: 'smash-cake', component: SmashCakeComponent },
    { path: 'famiglia', component: FamigliaComponent },
    { path: 'in-esterna', component: ServiziInEsternaComponent },
    { path: 'mini-sessioni', component: MiniSessioniComponent },
    { path: 'ritratto', component: RitrattoComponent },
    { path: 'newborn', component: NewbornComponent },
    { path: 'gallery/:servizio', component: GalleryPageComponent },
    { path: 'gallery/:servizio/detail', component: GalleryDetailComponent },
    { path: '**', redirectTo: '' }
  ];
